.TH DASH-CLI "1" "June 2016" "dashdiff-cli 0.12"
.SH NAME
dashdiff-cli \- a remote procedure call client for Dashdiff Core. 
.SH SYNOPSIS
dashdiff-cli [options] <command> [params] \- Send command to Dashdiff Core. 
.TP
dashdiff-cli [options] help \- Asks Dashdiff Core for a list of supported commands.
.SH DESCRIPTION
This manual page documents the dashdiff-cli program. dashdiff-cli is an RPC client used to send commands to Dashdiff Core.

.SH OPTIONS
.TP
\fB\-?\fR
Show possible options.

.SH "SEE ALSO"
\fBdashdiffd\fP, \fBdashdiff.conf\fP
.SH AUTHOR
This manual page was written by Ciemon Dunville <ciemon@gmail.com>. Permission is granted to copy, distribute and/or modify this document under the terms of the MIT License.

The complete text of the MIT License can be found on the web at \fIhttp://opensource.org/licenses/MIT\fP.
